http_enable = true
http_listen = "127.0.0.1:8080"
https_enable = true
https_listen = "127.0.0.1:8443"
tls_key_pem = ""
tls_cert_pem = ""
tls_key_perm_path = "pri.key"
tls_cert_perm_path = "cert.crt"

[[library]]
name = "media"
mount_point = "/data/media"
prefix = "webdav"

[[library]]
name = "backup"
mount_point = "/data/backup"
prefix = "webdav2"


[[scope]]
name = "media"
library = "media"
include = [
    "dir:/music",
    "dir:/vedio",
    "file:*.mp4"
]
exclude = [
    "dir:/xxx",
    "file:xxx.mp4"
]
permission = ["read", "write", "create_file", "create_folder", "rename"]

[[scope]]
name = "backup"
library = "backup"
include = [
    "dir:/"
]
exclude = [
]
permission = ["*"]

[[user]]
username = "test"
credential = "test"
scope = ["media", "backup"]

[safe]
password_retry_per_five_minute = 10
ban_user_wrong_pwd = true
ban_ip_wrong_pwd = true
